### ISSUE TITLE
Undefined indexes causes errors on some servers

### ISSUE THREAD

**Issue by monstahq** [monstahq/MONSTA-Box#1]
Because I haven't properly defined variables, on-screen errors appear if this level of error reporting is turned on in the PHP install.

**Comment by EC-Joe** [comment]
Variables should be properly defined, but as a stop gap while you work on cleaning stuff up you could probably just set the [error reporting level](http://php.net/manual/en/function.error-reporting.php) manually in your php script which would at least pretty things up for people who don't want to mess with their php configurations.

**Comment by monstaftp** [comment]
Thanks Joe. I have implemented this for v1.4.12.
