### ISSUE TITLE
hidden files

### ISSUE THREAD

**Issue by ploctaux** [monstahq/MONSTA-Box#18]
is there an option to show hidden files and folders?
because I need to work with hidden stuff

**Comment by megadr01d** [comment]
By default, hidden files are visible (there's no setting) so I'm pretty sure this is server dependent. Among several shared hosting services, I only found one that didn't display hidden files in Monsta FTP. I contacted support and they weren't able to help so I'm not sure what exactly prevents that.

**Comment by yiip87** [comment]
> I'm pretty sure this is server dependent.

Yup. FTP servers can be configured to not display hidden files.  
`ftp_rawlist()` takes arguments for the `LIST` command in the `$directory` parameter, i.e. 
```php
ftp_rawlist($conn, "-a /example/dir");
```
I think, that modifying [1] and [2] should be sufficent to force the listing of hidden files regardless of server side configuration.

[1] https://github.com/monstaftp/Monsta-FTP/blob/master/index.php#L755
[2] https://github.com/monstaftp/Monsta-FTP/blob/master/index.php#L845

**Comment by monstaftp** [comment]
I'll test this and include the option to view hidden files in the next release.

**Comment by loctauxphilippe** [comment]
@monstaftp good :-)

**Comment by monstahq** [comment]
The ability to show/hide files starting with a dot has been introduced in v1.8.4. Handling this manually was a better way as it allowed more flexibility than just doing "ls -a".

**Comment by ploctaux** [comment]
yay! :+1:
