### ISSUE TITLE
Login works, nothing visible

### ISSUE THREAD

**Issue by dodedodo** [monstahq/MONSTA-Box#56]
Hi!

I've tried to install monstaftp and everything seems to work normally, only there are no files or folders popping up. 
I can connect using filezilla from the same network so there's no routing problem, and the ftp server is accessible. Oh and phpinfo() tells me ftp support is enabled.

 I've ran the ftp server trough https://ftptest.net/ and it told me Warning: The server does not indicate MLSD support. Can this be the problem?

Thank you in advance for your quick reply. 

Sincerely,
Thijs de Vries

**Comment by dodedodo** [comment]
I forgot to mention that uploading/new file gives me an error aswell.

**Comment by dodedodo** [comment]
It seems to be fixed by adding $win_lin = "win"; manually hardcoded to the index.php. 

Only problem I still have is that I can't upload files. They are being uploaded to the monsta server, and the monsta server says it's uploading them to the ftp server but that doesn't happen. If the error persists i'll make a new issue for it soon.

**Comment by mmiat** [comment]
I've similar problem with debian 7.7
I can login, and I can create new folders, but I can't see anything
If I access with FileZilla, I see the folders created
I use FTP with TLS, I've tried with ftpMode=0 and ftpMode=1

**Comment by greecemunky** [comment]
@dodedodo The $win_lin variable is initially set based on the output of the LIST command issued.  If the output from your FTP server does not match any of Monsta FTP's criteria for determining the OS, it will remain blank.

In some scenarios no output may be returned (when an error occurs), but this doesn't affect you since your hard-coding of the $win_lin variable makes it work.

If you provide a test login I can test to try pinpoint the issue.

**Comment by monstaftp** [comment]
I think in version 2 it would be worthwhile having a fail error if it can't determine the platform based on ftp_rawlist().

**Comment by greecemunky** [comment]
@monstaftp In testing I have copied and modified one of your existing functions that does this, to generate a popup and force a logout if encountered.  I will submit this as a commit within the next couple of weeks.

**Comment by monstaftp** [comment]
That will be great, thanks.

**Comment by greecemunky** [comment]
Unfortunately I can't find the work I did on this, but it shouldn't take too long to re-do.  Expect something in the next week, if still required.

**Comment by monstahq** [comment]
Thanks but not necessary. We'll add this check in v2.0. 

It's also worth noting the function getPlatform() now uses the PHP function ftp_systype() so it's not based on ftp_rawlist() anymore (that was really ugly).
