### ISSUE TITLE
ZIP file corrupted

### ISSUE THREAD

**Issue by mghotz** [monstahq/MONSTA-Box#59]
Hello,

When i'm trying to download file(i'm using monsta ftp for my gallery project,only jpg files) or files(with zip) the are corrupted.I'm using 1.6.4 version.
I am tried this on different ftp accounts but result same. 
There is line break apperaing in the head of the page. How can solve this ?

**Comment by mghotz** [comment]
There is line break apperaing in the head of the page. How can solve this ?

**Comment by greecemunky** [comment]
Make sure your editing of Monsta's files (e.g. the config file) has not introduced a blank line at the very top.
Try again with the latest master.  I don't recall seeing this as a fixed issue, but it allows you to configure it again from scratch, in hope the issue doesn't reintroduce itself.

If it does, confirm other pages on your web site don't exhibit the same behaviour (blank line in HTML source).  If they do, then there is probably another source for the blank line.

**Comment by monstahq** [comment]
Zip downloads should now be working 100%.
